package com.linweili.miaosha.dao;

import com.linweili.miaosha.dataobject.UserPasswordDO;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Oct 25 12:24:40 SRET 2019
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Oct 25 12:24:40 SRET 2019
     */
    int insertSelective(UserPasswordDO record);
}